config/routes.rb
IngresosEgresos::Application.routes.draw do

  resources :tags, :suppliers
  
  resources :registers do
    collection do
      get 'search'
    end
  end

  root :to => 'registers#index'

end

app/models/register.rb
class Register < ActiveRecord::Base
  INCOME = 'ingreso'
  EGRESS = 'egreso'

  acts_as_taggable

  validates_presence_of :name, :date, :amount, :kind
  validates_inclusion_of :kind, in: [INCOME, EGRESS]
  validates_numericality_of :amount, greater_than: 0

  scope :by_date, order("date ASC")

  attr_accessible :date, :description, :amount, :folio, :name, 
                  :kind, :tag_list, :supplier_id
  
  belongs_to :supplier

  def income?
    kind == INCOME
  end

  def self.filter_by_date(start_date, end_date)
    results = self.where("date >= ?", start_date)
    results = results.where("date <= ?", end_date)
    results.by_date
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base

  validates_presence_of :name, :rfc
  attr_accessible :name, :rfc

  has_many :registers

  def self.suppliers_with_id_for_select
    Supplier.all.map do |supplier|
      [supplier.name, supplier.id]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  def new
    @suppliers = Supplier.suppliers_with_id_for_select
    @register = Register.new
  end

  def create
    @register = Register.new(params[:register]) 
    if @register.save
      redirect_to @register, notice: I18n.t("notice.register.created_successfully")
    else
      render :new
    end
  end

  def show
    @register = Register.find(params[:id])
  end

  def edit
    @suppliers = Supplier.suppliers_with_id_for_select
    @register = Register.find(params[:id])
  end

  def update
    @register = Register.find(params[:id])
    if @register.update_attributes(params[:register])
      redirect_to @register, notice: I18n.t("notice.register.updated_successfully")
    else
      render :edit
    end
  end

  def index
    @navigator = Services::Navigation.new(params[:start], params[:finish])
    @registers = Register.filter_by_date(@navigator.start_date, 
                                         @navigator.finish_date)
    @stats = Services::AccountingStats.new(@registers)
  end

  def search
    @navigator = Services::Navigation.new(params[:start], params[:finish])
    @registers = Register.filter_by_date(@navigator.start_date, @navigator.finish_date)
    @stats = Services::AccountingStats.new(@registers)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(params[:supplier])
    if @supplier.save
      redirect_to @supplier, notice: I18n.t("notice.supplier.created_successfully")
    else
      render :action => 'new'
    end
  end

  def show
    @supplier = Supplier.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    render :json => ActsAsTaggableOn::Tag.where('name LIKE ?', "%#{params[:term]}%").pluck(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/registers_helper.rb
module RegistersHelper

  def amount_for(register)
    if register.income?
      register.amount
    else
      register.amount * -1
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <%= link_to 'Innku', root_path, class: 'brand' %>
      <ul class="nav">
        <li><%= link_to 'Home', root_path%></li>
        <li><%= link_to 'Proveedores', new_supplier_path %></li>
      </ul>
    </div>
  </div>
  
  <div class='container'>
    <div>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </div>

</body>
</html>

app/views/registers/_form.html.erb
<%= form_for register, :html => {:class => 'form-inline'} do |f| %>
  <%= render 'shared/error_messages', object: register %>
  <p class='radio-button-holder'>
    <%= f.label :kind_ingreso, "Ingreso", class:'inline' %>
    <%= f.radio_button :kind, "ingreso" , :checked => 'checked'%>

    <%= f.label :kind_egreso, "Egreso", class:'inline' %>
    <%= f.radio_button :kind, "egreso" %>
  </p>
  <p>
    <%= f.label :date %><span class="help-inline required">*</span><br/>
    <%= f.text_field :date, class: "datepicker input-xlarge", readonly: 'true' %>
  </p>
  <p>
    <%= f.label :name %><span class="help-inline required">*</span><br/>
    <%= f.text_field :name, class: "input-xlarge" %>
  </p>
  <p>
    <%= f.label :amount %><span class="help-inline required">*</span><br/>
    <%= f.text_field :amount, class: "input-xlarge" %>
  </p>
  <p>
    <%= f.label :folio %><br/>
    <%= f.text_field :folio, class: "input-xlarge" %>
  </p>
  <p>
    <%= f.label :supplier_id %><br/>
    <%= f.select(:supplier_id, 
                  options_for_select(suppliers), prompt: "Elegir proveedor") %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, class: "input-xxlarge", rows: "3" %>
  </p>
  <p id="tags">
    <%= f.label :tag_list %><br/>
    <%= text_field_tag :new_tag, nil, class: "tags" %>
    <%= link_to "agregar", "#", :id => "add_tag" %>
    <%= f.hidden_field :tag_list %>
  </p>
  <p>
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancelar', :back , class: "btn btn-link" %>
  </p>

  <script>
    $(document).ready(function(e){

      new TagsApp(<%= f.object.tag_list.to_json.html_safe %>).render();
    })
  </script>

<% end %>

app/views/registers/_form_search.html.erb
<%= form_tag(search_registers_path, :method => 'get', :class => 'form-inline') do |f| %>
  <%= label_tag(:start, "De:") %>
  <%= text_field_tag(:start, l(@navigator.start_date), class: "datepicker") %>
  <%= label_tag(:finish, "Hasta:") %>
  <%= text_field_tag(:finish, l(@navigator.finish_date), class: "datepicker") %>
  <%= submit_tag("Buscar", class:"btn") %>
<% end %>

app/views/registers/_registers_list.html.erb
<table class='table table-striped'>
  <thead>
    <th>Fecha</th>
    <th>Concepto</th>
    <th>Folio</th>
    <th>Cantidad</th>
  </thead>
<% registers.each do |register| %>
  <tr class='link-to' data-url='<%= register_path(register) %>'>
    <td><%= l register.date %></td>
    <td><%= register.name %></td>
    <td><%= register.folio %></td>
    <td><%= amount_for register %></td>
  </tr>
<% end %>
</table>
<table class='table table-striped'>
  <tr>
    <td rowspan="2">Totales</td>
    <td>Ingresos</td>
    <td>Egresos</td>
    <td>Diferencia</td>
  </tr>
  <tr>
    <td><%= stats.incomes_total %></td>
    <td><%= stats.expenses_total %></td>
    <td><%= stats.difference_total %></td>
  </tr>
</table>

app/views/registers/edit.html.erb
<h1>
  Edición registro
</h1>

<%= render 'form', register: @register, suppliers: @suppliers %>

app/views/registers/index.html.erb
<div>
  <h1>Listado de Registros</h1>
</div>
<%= link_to '<i class="icon-plus icon-white"></i> Crear Registro'.html_safe, new_register_path, 
            :class => 'btn btn-primary', :id=>'create-register' %>
<div class='row-fluid navigator-register'>
  <div class='span4'>
    <%= link_to '<i class="icon-chevron-left"></i>'.html_safe, registers_path(start: @navigator.previous_month), :id=>'prev-month' %>
    <h2 class='inline'><%= l @navigator.start_date, :format => :month %></h2>
    <%= link_to '<i class="icon-chevron-right"></i>'.html_safe, registers_path(start: @navigator.next_month), :id=>'next-month' %>
  </div>
  <div class='span8 '>
    <%= render 'form_search' %>
  </div>
</div>

<%= render 'registers_list', registers: @registers, stats: @stats %>

app/views/registers/new.html.erb
<h1>
  Nuevo registro
</h1>

<%= render 'form', register: @register, suppliers: @suppliers %>

app/views/registers/search.html.erb
<h1>Búsqueda de registros</h1>
<%= link_to '<i class="icon-plus icon-white"></i> Crear Registro'.html_safe, new_register_path, 
            :class => 'btn btn-primary', :id=>'create-register' %>
<div class='row-fluid navigator-register'>
  <div class='span4'>
    <%= link_to 'Regresar al listado de registros', registers_path, :class => 'btn btn-link'%>
  </div>
  <div class='span8 '>
    <%= render 'form_search' %>
  </div>
</div>
<%= render 'registers_list', registers: @registers, stats: @stats %>

app/views/registers/show.html.erb
<h1><%= @register.name %></h1>
<p>
  <strong>Folio: </strong><span><%= @register.folio %></span>
</p>
<p>
  <strong>Concepto: </strong><span><%= @register.name %></span>
</p>
<p>
  <strong>Cantidad: </strong><span><%= @register.amount %></span>
</p>
<p>
  <strong>Fecha: </strong><span><%= l @register.date %></span>
</p>
<p>
  <strong>Tipo: </strong><span><%= @register.kind.titleize %></span>
</p>
<% if @register.supplier %>
<p>
  <strong>Proveedor: </strong><span><%= @register.supplier.name %></span>
</p>
<% end %>
<p>
  <strong>Detalle: </strong><span><%= @register.description %></span>
</p>
<p>
  <strong>Tags: </strong><span><%= @register.tag_list %></span>
</p>
<%= link_to 'Editar', edit_register_path(@register), class: "btn btn-primary" %>
<%= link_to 'Regresar al listado de registros', registers_path %>

app/views/shared/_error_messages.html.erb
<% if(object.errors.any?) %>
  <ul>
    <% object.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <%end%>
  </ul>
<% end %>

app/views/suppliers/new.html.erb
<h1>Nuevo proveedor</h1>
<%= form_for @supplier , :html => {:class => 'form-inline'} do |f| %>
  <%= render 'shared/error_messages', object: @supplier %>
  <p>
    <%= f.label :name %><span class="help-inline required">*</span><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :rfc %><span class="help-inline required">*</span><br/>
    <%= f.text_field :rfc %>
  </p>
  <p>
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancelar', :back , class: "btn btn-link" %>
  </p>
<% end %>

app/views/suppliers/show.html.erb
<p>
  <strong>Nombre: </strong><span><%= @supplier.name %></span>
</p>
<p>
  <strong>RFC: </strong><span><%= @supplier.rfc %></span>
</p>
<%= link_to 'Regresar al listado de registros', registers_path %>